const Moralis = require('moralis').default;
const { EvmChain } = require('@moralisweb3/evm-utils');

const runApp = async () => {
  await Moralis.start({
    apiKey: "oTaHYuC1KAGCe9MmBipl9sPmgr05Xau240KFWsX06H0jiErUt1Cp15b867nAD0ix",
    // ...and any other configuration
  });
  
    const abi = [
    {
        path: "cars/metadata/1.json",
        content: "ewogICAgIm5hbWUiOiAiTWFydXRpIEJhbGVubyIsCiAgICAiZGVzY3JpcHRpb24iOiAiTWFydXRpIEJhbGVubyBpcyBhIDUgc2VhdGVyIEhhdGNoYmFjay4gSXQgaXMgYXZhaWxhYmxlIGluIDkgdmFyaWFudHMsIGEgMTE5NyBjYywgQlM2IGFuZCAyIHRyYW5zbWlzc2lvbiBvcHRpb25zOiBNYW51YWwgJiBBdXRvbWF0aWMiLAogICAgImltYWdlIjogImh0dHBzOi8vaXBmcy5tb3JhbGlzLmlvOjIwNTMvaXBmcy9RbVgxVzdwNTVtaXJyOFVWWG5IbWlUc2VWaWZtaHNXZEs5Y1hhZGIyb1M4MkhEL21pbGxvdy9jYXJzL2JhbGVuby5wbmciLAogICAgImlkIjogIjEiLAogICAgImF0dHJpYnV0ZXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJQdXJjaGFzZSBQcmljZSIsCiAgICAgICAgICAgICJ2YWx1ZSI6IDYuNgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJNaWxlYWdlIiwKICAgICAgICAgICAgInZhbHVlIjogIjMwLjYxIGttL2tnIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJFbmdpbmUgKHVwdG8pIiwKICAgICAgICAgICAgInZhbHVlIjogIjExOTcgY2MiCgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJCb290IFNwYWNlIiwKICAgICAgICAgICAgInZhbHVlIjogMzE4CiAgICAgICAgfQogICAgXQp9",
    },
    {
        path: "cars/metadata/2.json",
        content: "ewogICAgIm5hbWUiOiAiTWVyY2VkZXMtQmVueiBBTUcgR1QiLAogICAgImRlc2NyaXB0aW9uIjogIk1lcmNlZGVzLUJlbnogaXMgYSAyIHNlYXRlciBMdXh1cnkuIEl0IGlzIGF2YWlsYWJsZSB3aXRoIEF1dG9tYXRpYyB0cmFuc21pc3Npb24uIiwKICAgICJpbWFnZSI6ICJodHRwczovL2lwZnMubW9yYWxpcy5pbzoyMDUzL2lwZnMvUW1aYmFudkdFZ1BCZFk1R1RoeDVpeDZxUDY0dkNuZE5ncUxHWHdLWjF6Ykw2VC9taWxsb3cvY2Fycy9tZXJjZWRlcy5wbmciLAogICAgImlkIjogIjIiLAogICAgImF0dHJpYnV0ZXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJQdXJjaGFzZSBQcmljZSIsCiAgICAgICAgICAgICJ2YWx1ZSI6IDIwMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJNaWxlYWdlIiwKICAgICAgICAgICAgInZhbHVlIjogIjEyLjY1IGttcGwiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJ0cmFpdF90eXBlIjogIkVuZ2luZSAodXB0bykiLAogICAgICAgICAgICAidmFsdWUiOiAiMzk4MiBjYyIKCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJ0cmFpdF90eXBlIjogIkJvb3QgU3BhY2UiLAogICAgICAgICAgICAidmFsdWUiOiAyODUKICAgICAgICB9CiAgICBdCn0=",
    },
    {
        path: "cars/metadata/3.json",
        content: "ewogICAgIm5hbWUiOiAiRmVycmFyaSBTRjkwIFN0cmFkYWxlIiwKICAgICJkZXNjcmlwdGlvbiI6ICJGZXJyYXJpIFNGOTAgU3RyYWRhbGUgaXMgYSAyIHNlYXRlciBDb3VwZS4gSXQgaXMgYXZhaWxhYmxlIHdpdGggQXV0b21hdGljIHRyYW5zbWlzc2lvbi4iLAogICAgImltYWdlIjogImh0dHBzOi8vaXBmcy5tb3JhbGlzLmlvOjIwNTMvaXBmcy9RbVJ4TkdzWVYxd1Q5Z0V1ZWlFV1RiS3hSUWtZVlZLZmZyVWJoaW9lWXhuWmZnL21pbGxvdy9jYXJzL2ZlcnJhcmkucG5nIiwKICAgICJpZCI6ICIzIiwKICAgICJhdHRyaWJ1dGVzIjogWwogICAgICAgIHsKICAgICAgICAgICAgInRyYWl0X3R5cGUiOiAiUHVyY2hhc2UgUHJpY2UiLAogICAgICAgICAgICAidmFsdWUiOiA3NQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAidHJhaXRfdHlwZSI6ICJNaWxlYWdlIiwKICAgICAgICAgICAgInZhbHVlIjogIjE2LjM5IGttcGwiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJ0cmFpdF90eXBlIjogIkVuZ2luZSAodXB0bykiLAogICAgICAgICAgICAidmFsdWUiOiAiMzk5MCBjYyIKCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJ0cmFpdF90eXBlIjogIlNlYXRzIiwKICAgICAgICAgICAgInZhbHVlIjogMgogICAgICAgIH0KICAgIF0KfQ==",
    },
    ];

  const response = await Moralis.EvmApi.ipfs.uploadFolder({ abi });
  
  console.log(response.toJSON());
}

runApp();